# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'db_table': 'blog_categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='название')),
                ('description', models.TextField(verbose_name='пост')),
                ('pub_date', models.DateField(auto_now_add=True, db_index=True)),
                ('likes', models.IntegerField(default=0, verbose_name='Кол. лайков:')),
                ('previews', models.IntegerField(default=0, verbose_name='Кол-во просмотров:')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.BlogCategory', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
                'db_table': 'posts',
            },
        ),
    ]
